## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_nosql_demos_1 {
  compartment_id = var.compartment_ocid
  config = {
    "NOSQL_COMPARTMENT_ID" = var.compartment_ocid
    "NOSQL_REGION"         = var.region
  }
  defined_tags = {
  }
  display_name = "nosql_demos"
  freeform_tags = {
  }
  subnet_ids = [
    oci_core_subnet.export_Public-Subnet-vcn_nosql_demos.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

