## This configuration was generated by terraform-provider-oci

resource oci_apigateway_gateway export_nosql_demos {
  #certificate_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name  = "nosql_demos"
  endpoint_type = "PUBLIC"
  freeform_tags = {
  }
  response_cache_details {
    #authentication_secret_id = <<Optional value not found in discovery>>
    #authentication_secret_version_number = <<Optional value not found in discovery>>
    #connect_timeout_in_ms = <<Optional value not found in discovery>>
    #is_ssl_enabled = <<Optional value not found in discovery>>
    #is_ssl_verify_disabled = <<Optional value not found in discovery>>
    #read_timeout_in_ms = <<Optional value not found in discovery>>
    #send_timeout_in_ms = <<Optional value not found in discovery>>
    #servers = <<Optional value not found in discovery>>
    type = "NONE"
  }
  subnet_id = oci_core_subnet.export_Public-Subnet-vcn_nosql_demos.id
}

resource oci_apigateway_deployment export_BaggageDemo {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "BaggageDemo"
  freeform_tags = {
  }
  gateway_id  = oci_apigateway_gateway.export_nosql_demos.id
  path_prefix = "/BaggageDemo"
  specification {
    logging_policies {
      #access_log = <<Optional value not found in discovery>>
      execution_log {
        is_enabled = "true"
        log_level  = "INFO"
      }
    }
    request_policies {
      #authentication = <<Optional value not found in discovery>>
      #cors = <<Optional value not found in discovery>>
      #rate_limiting = <<Optional value not found in discovery>>
    }
    routes {
      backend {
        #body = <<Optional value not found in discovery>>
        #connect_timeout_in_seconds = <<Optional value not found in discovery>>
        function_id = oci_functions_function.export_demo-api.id
        #headers = <<Optional value not found in discovery>>
        #is_ssl_verify_disabled = <<Optional value not found in discovery>>
        #read_timeout_in_seconds = <<Optional value not found in discovery>>
        #send_timeout_in_seconds = <<Optional value not found in discovery>>
        #status = <<Optional value not found in discovery>>
        type = "ORACLE_FUNCTIONS_BACKEND"
        #url = <<Optional value not found in discovery>>
      }
      logging_policies {
        #access_log = <<Optional value not found in discovery>>
        execution_log {
          #is_enabled = <<Optional value not found in discovery>>
          log_level = ""
        }
      }
      methods = [
        "ANY",
      ]
      path = "/{api}"
      request_policies {
        #authorization = <<Optional value not found in discovery>>
        #body_validation = <<Optional value not found in discovery>>
        #cors = <<Optional value not found in discovery>>
        #header_transformations = <<Optional value not found in discovery>>
        #header_validations = <<Optional value not found in discovery>>
        #query_parameter_transformations = <<Optional value not found in discovery>>
        #query_parameter_validations = <<Optional value not found in discovery>>
        #response_cache_lookup = <<Optional value not found in discovery>>
      }
      response_policies {
        #header_transformations = <<Optional value not found in discovery>>
        #response_cache_store = <<Optional value not found in discovery>>
      }
    }
  }
}

