## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_nosql_demos_1 {
  compartment_id = var.compartment_ocid
  config = {
    "NOSQL_COMPARTMENT_ID" = var.compartment_ocid
    "NOSQL_REGION"         = var.region
  }
  defined_tags = {
  }
  display_name = "nosql_demos"
  freeform_tags = {
  }
  subnet_ids = [
    oci_core_subnet.export_Public-Subnet-vcn_nosql_demos.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

resource oci_functions_function export_demo-api {
  depends_on     = [null_resource.demo-apiPush2OCIR]
  application_id = oci_functions_application.export_nosql_demos_1.id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-api"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-api:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_demo-keyval-load {
  depends_on     = [null_resource.demo-keyval-loadPush2OCIR]
  application_id = oci_functions_application.export_nosql_demos_1.id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-keyval-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-keyval-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_demo-load {
  depends_on     = [null_resource.demo-loadPush2OCIR]
  application_id = oci_functions_application.export_nosql_demos_1.id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}


