## This configuration was generated by terraform-provider-oci


resource oci_streaming_stream export_nosql_demos_3 {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  freeform_tags = {
  }
  name               = "nosql_demos"
  partitions         = "1"
  retention_in_hours = "24"
  #stream_pool_id = <<Optional value not found in discovery>>
}

