kind: Service
apiVersion: v1
metadata:
  name: books
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
        version: v1
    spec:
      containers:
      - name: books
        image: books
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
