apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-nosql-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      express-nosql: web
  template:
    metadata:
      labels:
        express-nosql: web
    spec:
      containers:
      - name: express-nosql
        image: iad.ocir.io/oradbclouducm/nosqldemos/express-nosql:latest
        imagePullPolicy: Always
        ports:
        - name: express-nosql
          containerPort: 3000
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: express-nosql-demo
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.iad.aaaaaaaare35jyktjq24hoesxxfcs5vbur72t5fmexlclsxncrelm2jfmrcq"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    express-nosql: web
  type: LoadBalancer
status:
  loadBalancer: {}
